### ISSUE TITLE
Specify electron version to use

### ISSUE THREAD

**Issue by zoltan-mihalyi** [apache/cordova-electron#185]
# Feature Request

## Motivation Behind Feature

It would be possible to use the latest electron features and fixes.

## Feature Description

build.json:
```json
{
  "electron": {
     "electronVersion": "11.1.1"
  }
}
```

## Alternatives or Workarounds

I am experimenting with changing version in electron/package.json, removing electron/dist folder and runnning electron/install.js

**Comment by erisu** [comment]
This request has been mentioned a few times but it is a bit challenging.

There are two places where the version is defined. 
The `package.json` of the platform. This dependency is used for the `cordova run` command. Currently, the pinning contains `^` which accepts new minor and patches. This `^` is problematic and should be hard pin to follow the second location. The reason it is problematic is that the run command may eventually fail which no changes to the user's project.
The `build.json` is hard pinned. This is used for building the packages. Because it is hard pinned, it is consistent and should not fail unexpectedly if there is no change to the project. This is used in the `cordova build` command.
If we allow the users to specify a version, we can not guarantee that the project will build or run successfully. Nor can we provide speedy support.

Something could be implemented for experimental purposes, but reported issue tickets of unsupported dependencies may get closed immediately or thrown in a backlog which might over time get forgotten. Also with changes to Electron, there might be changes required for the builder.

I had taken a look into potentially using a post-install script to manage to install the targeted version during platform add but the post-install script was not being executed as expected.

Shortly, I will be changing the pinning in `package.json` to be hard pinned to resolve the current issue where the `cordova run` outcome might not match with `cordova build`, but whatever solution you had in mind needs to support both run and build and also how to resolve builder dependency matching with the electron version they wanted.

**Comment by zoltan-mihalyi** [comment]
I think the `config.xml` is the right place:
```json
    <platform name="electron">
        <preference name="ElectronVersion" value="11.2.0" />
    </platform>
```
Maybe the preference name should be "ExperimentalElectronVersion".

Using this version in `build` seems an easy task to me, but it is difficult in `run`, because we should install electron with the given version.

Installing electron would happen in `prepare`. I can see two solutions:
- install `electron` with npm somewhere in platform folder
- use `@electron/get` directly, and implement code similar to `electron/install.js` (version check, download, extract, determine executeble path)

What do you think?
