### ISSUE TITLE
cordova-electron is support require function

### ISSUE THREAD

**Issue by CHHHAN** [apache/cordova-electron#278]
I want use `child_process` and Invoke the command line.
but is result: `require is not defined`
This question has been bothering me for three days and three nights.

Command
```
cordova create sampleApp
cd sampleApp
cordova platform add electron
cordova run electron --nobuild
```

packjson.json
```
{
  "name": "io.cordova.hellocordova",
  "displayName": "HelloCordova",
  "version": "1.0.0",
  "description": "A sample Apache Cordova application that responds to the deviceready event.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "ecosystem:cordova"
  ],
  "author": "Apache Cordova Team",
  "license": "Apache-2.0",
  "devDependencies": {
    "cordova-electron": "^4.0.0",
    "cordova-plugin-device": "^2.1.0"
  },
  "cordova": {
    "platforms": [
      "electron"
    ],
    "plugins": {
      "cordova-plugin-device": {}
    }
  }
}

```

index.js
```
document.addEventListener('deviceready', onDeviceReady, false);

function onDeviceReady() {
    // Cordova is now initialized. Have fun!

    const { app } = require('electron');
    console.log(app)

    console.log('Running cordova-' + cordova.platformId + '@' + cordova.version);
    document.getElementById('deviceready').classList.add('ready');
}
```

console result:
```
Uncaught ReferenceError: require is not defined
    at Channel.onDeviceReady (index.js:27:21)
    at Channel.fire (cordova.js:827:23)
    at cordova.js:232:49
```

**Comment by breautek** [comment]
electron has 2 processes, a webview process and a nodejs process. In Cordova, the NodeJS process is akin to the "native" process seen in other platforms. It's only exposed to plugins. Your web app lives in the webview process which does not run in a NodeJS environment and therefore doesn't have access to the `require` method, like other browser environments.

In order to use NodeJS APIs you will have to create a cordova plugin that implements an interface into the NodeJS API. We don't have a guide available at this time, but the [device plugin](https://github.com/apache/cordova-plugin-device/tree/master/src/electron) can be used as an example. The notable files are:

- `/plugin.xml` for to see how things are binded
- `/src/electron` for the nodejs implementation for the cordova API
- `/www/device.js` (https://github.com/apache/cordova-plugin-device/blob/master/www/device.js#L91) which is the webview implementation of the plugin, that calls on the native API.

Note that it's important to restrict access to only what is necessary by the webview side. For example, the full ChildProcess/spawn APIs should not be exposed to the webview as that can be used as an exploit.

If you have further questions on how to build an electron plugin or integrating them, please use [Cordova Discussions](https://github.com/apache/cordova/discussions).
