### ISSUE TITLE
"[Cordova Electron] The built package size may be larger than necessary."

### ISSUE THREAD

**Issue by Polm90** [apache/cordova-electron#88]
I'm using cordova-electron 1.1.0 with cordova 9.0.0 (on windows).
Everytime I add a plugin, I receive this warning:

"[Cordova Electron] The built package size may be larger than necessary."

What does it mean? And what are the implications?

**Comment by erisu** [comment]
@Polm90 The way Cordova currently operates when adding a Cordova platform or plugins, is that they are added to the project's `dependencies` in `package.json`. These platforms and plugins should actually be added as `devDependencies` because the contents are never used directly.  There is a PR to correct this but won't be released until the next major of Cordova.

The reason they should be `devDependencies` is that only relevant files are copied to the appropriate location (E.g. `platforms/<platform>` dir) and used during build time.

With Electron, to support node modules bundling, we use the project `dependencies` as the Electron app dependencies. These means the list of `dependencies` is copied over to the Electron app.

During the prepare step, we check the `dependencies` list for any module that matches `/^cordova(?!-plugin)-/`. If any matches, we just warn the user that the bundle app can be larger then expected.

Example:
* Create a new project
* Add the electron platform
* build project

```
144M    platforms/electron/build/HelloCordova-1.0.0.dmg
```

Notice that the `package.json` has this:
```
"dependencies": {
    "cordova-electron": "^1.1.0"
  },
  "devDependencies": {
    "cordova-plugin-whitelist": "^1.3.4"
  },
```
We can move manually `"cordova-electron": "^1.1.0"` to `devDependencies` to make this:
```
"dependencies": {
  },
  "devDependencies": {
    "cordova-electron": "^1.1.0",
    "cordova-plugin-whitelist": "^1.3.4"
  },
```
When we rebuild the project:

```
52M    platforms/electron/build/HelloCordova-1.0.0.dmg
```
the app size becomes smaller. This is because the `cordova-electron` dependency is no longer bundled with the app.

**Comment by Polm90** [comment]
So, I should move the cordova plugins and platforms from "dependencies" to "devDependencies", am I right?

Thank you for your answer: it's very clear!

**Comment by erisu** [comment]
Yes, that would be the best option. It will remove the warning, the Electron final built app size remain small, and bundle only the relevant modules. Additionally, there should be NO side-effects with the existing Cordova tooling or other platforms.

**Comment by Polm90** [comment]
Thank you.
But I noticed that running the command "cordova prepare", all platforms except cordova-electron (ie, browser, android, ios) are automatically copied in the "dependencies" section, so that the warning is still present.
Is this behaviour due to cordova?

Thank you again

**Comment by erisu** [comment]
Can you give me a step-by-step that reproduces that?

If you installed other platforms with `cordova platform add` they will go to `dependencies`, as mentioned before.

Example:
```
cordova platform add android
```
generates:
```
"dependencies": {
    "cordova-android": "^8.0.0"
  },
  "devDependencies": {
    "cordova-electron": "^1.1.0",
    "cordova-plugin-whitelist": "^1.3.4"
  },
```

But you would need to move them manually to `devDependencies` as well.

```
"dependencies": {
  },
  "devDependencies": {
    "cordova-android": "^8.0.0",
    "cordova-electron": "^1.1.0",
    "cordova-plugin-whitelist": "^1.3.4"
  },
```

When running `cordova prepare`, it should not move or copy them back to `dependencies`. It should remain as `devDependencies`:

```
"dependencies": {
  },
  "devDependencies": {
    "cordova-android": "^8.0.0",
    "cordova-electron": "^1.1.0",
    "cordova-plugin-whitelist": "^1.3.4"
  },
```

**Comment by erisu** [comment]
Also, for reference, this is the PR that I was talking about that will change how `platform add` and `plugin add` will save them as `devDependencies` instead of `dependencies`.

https://github.com/apache/cordova-fetch/pull/65

**Comment by Polm90** [comment]
I did as you described, but after "cordova prepare" I have the platform both in "dependencies" and in "devDependencies".
But probably with the PR you linked, it will be fixed.
Thank you
